name: sveltekit-portfolio
region: sgp

services:
  - name: web
    # GitHub repository
    github:
      repo:  your-username/your-repo
      branch: main
      deploy_on_push: true

    # ❌ XÓA dòng dockerfile_path
    # Thay vào đó dùng buildpack
    environment_slug: node-js

    # Build và run commands
    build_command: npm install && npm run build
    run_command: node build/index.js

    # Port app listen
    http_port: 8080

    # Instance configuration
    instance_count: 1
    instance_size_slug:  basic-xxs

    # Routes
    routes:
      - path: /

    # Health check (optional)
    health_check:
      http_path: /
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    # Environment variables
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3000"
